---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - 'git'
  - 'chromium'
  - 'gnome-tweaks'
  - 'gnome-shell-extension-openweather'
  - 'gpaste' 
  - 'gpaste-ui' 
  - 'gnome-shell-extension-gpaste'
  - 'gnome-shell-extension-topicons-plus.noarch'
  - 'gnome-shell-extension-user-theme.noarch '
  - 'gnome-shell-extension-apps-menu.noarch'
  - 'gnome-shell-extension-places-menu.noarch'
  - 'gnome-shell-extension-openweather.noarch'
  - 'gnome-shell-extension-background-logo.noarch'
  - 'gnome-shell-extension-dash-to-dock.noarch '
  - 'snapd'
  - 'vlc'
  - 'megasync'

- name: Create a symlink for snapd
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  
- name: Install Snap packages
  snap:
    name:
      - postman
      - dbeaver-ce
 
- name: Install Snap packages with --classic flag
  snap:
    classic: yes
    name:
      - node
      - code
      - spotify
      - docker
      - dotnet-sdk
        
